import './globals.css'
import React from 'react';
import './globals.css';
import Header from './Header';
import Footer from '../src/app/Footer';

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayout;
